### PR TITLE
Updated .gitignore to exclude __init__.py files

### PR DESCRIPTION
**Pull request by parthjdoshi**

### CODE REVIEW

**Review by ikbalsingh — COMMENTED** [review]
Still ignores __init__.py.

**Comment by parthjdoshi** [comment]
Where are just init.py files used?

**Comment by ikbalsingh** [comment]
I meant the --init--.py inside migrations. It is still being ignored by the gitignore.

**Review by ikbalsingh — APPROVED** [review]
Solves #6

**Pull request merged**
