### PR TITLE
Restructured the entire project

### PR DESCRIPTION
**Pull request by AvaisP**
Solves #4

### CODE REVIEW

**Comment by parthjdoshi** [comment]
Are we supposed to include binary files as well?

**Comment by AvaisP** [comment]
No. All of that needs to go

**Comment by parthjdoshi** [comment]
You have kept them in. Could you delete them? I am not sure if we have write access.

**Comment by AvaisP** [comment]
We'll remove all of that once we add gitignore

**Review by parthjdoshi — APPROVED** [review]

**Pull request merged**
