### PR TITLE
Initial Commit

### PR DESCRIPTION
**Pull request by viral98**

### CODE REVIEW

**Comment by AvaisP** [comment]
21,651 files changed :|

**Comment by AvaisP** [comment]
@krishamehta Please review

**Comment by AvaisP** [comment]
@krishamehta This has been pending for over a week now

**Comment by krishamehta** [comment]
Please solve all the bugs first.

**Comment by krishamehta** [comment]
Push all the changes you made

**Comment by viral98** [comment]
All the changes regarding login page have been pushed in this branch.

**Comment by AvaisP** [comment]
@krishamehta Review!

**Comment by AvaisP** [comment]
Merge master into this and add node_modules to gitignore

**Pull request closed without merging**
